### PR TITLE
Update presenter-MarneeDear.md

### PR DESCRIPTION
**Pull request by MarneeDear**
I added some notes.

Can you guys provide 4 ethernet cables? 
Will the power strip work for USA sockets and will it have an adapter?

### CODE REVIEW

**Comment by parkan** [comment]
thanks for the update, will forward the equipment request to the production folks!

**Comment by parkan** [comment]
@doctorrobinson can we use one of your bagels for this? if it has 4 slots then we'll need 2, right?

**Comment by MarneeDear** [comment]
Thank @parkan . I will need a power strip with 6 US sockets and an wall socket adapter to plug it in to. I have my own, but if you all can provide one, and the Ethernet cables, that would help me be able to transport all the other equipment.

**Comment by doctorrobinson** [comment]
The bagel has 5 US power sockets (4 are universal) and 2 USB outs - you can borrow one as long as we don't have any recordings going on concurrently, which it doesn't look like it is currently, unless someone wants to record Unconf.

**Comment by parkan** [comment]
@MarneeDear we gotchu with the cat5e (4x1m), US power strips are a bit difficult to source here but we will try to make do with the [MOGICS Bagels](http://www.mogics.com/3824-2) -- PL folks tend to travel with these and we should be able to borrow at least one, hopefully 2 

will that work for you?

bagel

**Pull request merged**
