### PR TITLE
Update 37-ipfs-in-web-workers.md with conclusions from deep dive

### PR DESCRIPTION
**Pull request by aknuds1**
Describe conclusions from deep dive.

### CODE REVIEW

**Comment by Gozala** [comment]
@aknuds1 do you by a chance know a handle of the third participant ?

**Comment by Gozala** [comment]
@zeckli

**Comment by Gozala** [comment]
@zeckli do you want to come up the stage as we'll be presenting our work ?

**Review by alanshaw — APPROVED** [review]
Thanks @gozala, @aknuds1, @zeckli 🚀 ❤️

**Pull request merged**
