### PR TITLE
Deep Dive Report Back: Reproducible CIDs

### PR DESCRIPTION
**Pull request by lidel**
@lidel and @drbh around 14:35:

### CODE REVIEW

**Review by drbh — APPROVED** [review]
LGTM

**Comment by alanshaw** [comment]
@lidel / @drbh any chance you can fix these conflicts?

**Comment by lidel** [comment]
@alanshaw done

**Review by alanshaw — APPROVED** [review]
Thanks @lidel, @drbh ❤️ 🚀

**Comment by drbh** [comment]
started a repo with a `revive` add option here: https://github.com/ipfs/go-ipfs/compare/master...drbh:force-default-params

**Comment by lidel** [comment]
@drbh that's really cool! 

Consider submitting a [wip] or Draft PR, so we have a place to discuss implementation details and gather early feedback there :)

**Comment by drbh** [comment]
Added a WIP PR here https://github.com/ipfs/go-ipfs/pull/6509

**Pull request merged**
