### PR TITLE
Added notes from the user testing walk-through.

### PR DESCRIPTION
**Pull request by cesarosum**

### CODE REVIEW

**Comment by tetrisgm** [comment]
Looks solid! Could you please add that we covered the design process used
in Stanford D School and the basics of design thinking?
Also I prefer to go by my nick than my name :)

**Comment by jessicaschilling** [comment]
Just PR-bombing to say that this is great :)

**Review by tetrisgm — APPROVED** [review]

**Review by AquiGorka — APPROVED** [review]
❤️ 🎉

**Comment by cesarosum** [comment]
@alanshaw This is ready to merge.

**Review by alanshaw — APPROVED** [review]
Thanks @leshokunin, @AquiGorka, @cesarosum, @aksanoble, @vrortvedt, @makoto ❤️ 🚀

**Pull request merged**
