### PR TITLE
02-scaling-up-the-dht: proposal with implementation details

### PR DESCRIPTION
**Pull request by Prtfw**

### CODE REVIEW

**Comment by Prtfw** [comment]
@Stebalien @koalalorenzo  @Prtfw @obo20 @MichaelMure @gregdhill  @kumavis

**Comment by Prtfw** [comment]
@obo20 oopsies conflicts : ) do you want resolve them or do you want me to?

**Comment by obo20** [comment]
@Prtfw Feel free to go ahead and resolve them. I mainly made my updates as I couldn't find your branch for some reason.

**Review by koalalorenzo — APPROVED** [review]

**Review by alanshaw — APPROVED** [review]
Thanks @Stebalien @koalalorenzo @prtfw @obo20 @MichaelMure @gregdhill @kumavis ❤️ 🚀

I've resolved the conflict as best I could - please have a read and if it doesn't make sense please send a PR to fix 😁

**Pull request merged**
