### PR TITLE
Fixed spelling in dir name LIGHTING -> LIGHTNING

### PR DESCRIPTION
**Pull request by avras**
I am obsessed with spelling. Sorry :)

### CODE REVIEW

**Review by alanshaw — APPROVED** [review]

**Comment by jessicaschilling** [comment]
I saw this as well when I inherited the document :( but am fearful that there are enough places that direct-link to it by name that renaming the doc will cause more trouble than it’s worth. I hate to leave a typo but given the situation (and that it has been fixed everywhere in running text), suggest that we do.

**Comment by avras** [comment]
I did not think of the direct-link dependencies this change might break. In case someone does want to fix it in the future, the phrase "LIGHTING_TALKS" appears once in the ipfs/camp repo and once in the ipfs/camp.ipfs.io repo.

[https://github.com/ipfs/camp/search?q=LIGHTING_TALKS&unscoped_q=LIGHTING_TALKS](https://github.com/ipfs/camp/search?q=LIGHTING_TALKS&unscoped_q=LIGHTING_TALKS)

[https://github.com/ipfs/camp.ipfs.io/search?q=LIGHTING_TALKS&unscoped_q=LIGHTING_TALKS](https://github.com/ipfs/camp.ipfs.io/search?q=LIGHTING_TALKS&unscoped_q=LIGHTING_TALKS)

**Comment by jessicaschilling** [comment]
@avras Thanks for doing the search due-diligence on that one 😄 Unfortunately, there's also a series of reference emails and a few other artifacts that aren't trackable via GitHub. Good call on fixing in the future though!

**Comment by avras** [comment]
Can we fix the spelling in the Camp schedule? Please!! I need my fix!!

[https://github.com/ipfs/camp.ipfs.io/search?q=lighting](https://github.com/ipfs/camp.ipfs.io/search?q=lighting)

**Comment by jessicaschilling** [comment]
@cwaring -- are you able to fix "lightning" for "lighting" in the running text here? https://camp.ipfs.io/schedule
I'm reluctant to change the path to the .md itself because of the reasons above, but it'd be great to get the actual text on the camp schedule corrected. Thank you!

**Comment by cwaring** [comment]
@jessicaschilling not sure how this one passed our revisions! I'll change it on the site and it would be best to update here once all the content is compiled so you're not depending on those inbound links.

**Comment by jessicaschilling** [comment]
@cwaring - thanks! Unfortunately a number of emails with instructions for presenters etc are linking to the misspelled md file name, so I’m loathe to change the name of the md file itself. But if you could fix the misspellings on the running text of the camp website, that’d be awesome. Make sense? 😊

**Comment by cwaring** [comment]
@jessicaschilling agree I've updated the site but I was suggesting that we revisit renaming in the repo closer to camp after the bulk of the content has been compiled and before "officially" going public.

**Comment by daviddias** [comment]
I'm terribly sorry. This typo is my fault :(

> @jessicaschilling agree I've updated the site but I was suggesting that we revisit renaming in the repo closer to camp after the bulk of the content has been compiled and before "officially" going public.

@cwaring do you mean that it is best to change now before the Events team sends the big announcement with content next Tuesday?

**Comment by daviddias** [comment]
> Unfortunately a number of emails with instructions for presenters etc are linking to the misspelled md file name, so I’m loathe to change the name of the md file itself.

We could potentially have a file on the place with the typo just to redirect folks

**Comment by jessicaschilling** [comment]
@daviddias - I’m cool with having the misspelled doc just say “this was moved, click here” ... but I’m getting on a plane in a few and so it’d be a bit before I could do this myself.

**Comment by jessicaschilling** [comment]
OK, changed the following:
1. Readme in directory https://github.com/ipfs/camp/tree/master/LIGHTING_TALKS now just has "info moved, click here" language
2. New directory with content from original readme: https://github.com/ipfs/camp/tree/master/LIGHTNING_TALKS
3. Inbound link from readme at https://github.com/ipfs/camp now points to new location
4. @cwaring, can you please note the above and change camp site accordingly? I believe at present all this means is:
- Un-misspelling the URL to the modal https://camp.ipfs.io/schedule/format/lighting on the page https://camp.ipfs.io/schedule
- changing the contentURL as noted here: https://github.com/ipfs/camp.ipfs.io/search?q=LIGHTING_TALKS&unscoped_q=LIGHTING_TALKS

Please let me know if I can help with anything. Thank you!

**Comment by cwaring** [comment]
ace, I'll get that updated 👍

**Comment by jessicaschilling** [comment]
Woohoo, thanks @cwaring!
@avras, your wish has been granted ;) ... going to close this issue now. See you in Barcelona!

**Comment by avras** [comment]
> Woohoo, thanks @cwaring!
> @avras, your wish has been granted ;) ... going to close this issue now. See you in Barcelona!

Thank you @jessicaschilling, @cwaring for the fixes and @daviddias for the redirection idea.

**Pull request closed without merging**
