### PR TITLE
Add Elective Course A description

### PR DESCRIPTION
**Pull request by satazor**

### CODE REVIEW

**Comment by momack2** [comment]
Thanks Andre! Can you also update here: https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_A?

**Comment by satazor** [comment]
Done.

**Comment by momack2** [comment]
Thanks! Do you have any list of "what you will learn" and "what you should prepare for this course"?

**Review by alanshaw — APPROVED** [review]

**Comment by satazor** [comment]
@momack2 I will fill those soon, writing this on my phone.

**Comment by satazor** [comment]
Updated! Looking good?

**Comment by momack2** [comment]
Looks great! Merging. =]

**Pull request merged**
